---
# Handlers para gaming server

- name: restart_gaming_services
  ansible.builtin.debug:
    msg: "ğŸ”„ Servicios gaming reiniciados despuÃ©s de cambios en configuraciÃ³n"

- name: reload_firewall
  ansible.builtin.service:
    name: ufw
    state: reloaded
  listen: reload_firewall

- name: restart_steam_services
  ansible.builtin.debug:
    msg: "ğŸ® Servicios Steam reiniciados"